### ISSUE TITLE
[ENHANCEMENT]  Offload greenchecks into parquet file for easier analysis

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/admin-portal#276]
**Is your feature request related to a problem? Please describe.**

We have a series of colossal greencheck tables that every check is logged to each time someone, or some machine does a greencheck. These take up loads of space, and are a pain to work with in MySQL

**Describe the solution you'd like**

Every day, or every week, we export all the greenchecks in a compressed form that we can easily query, and ship them to object storage.

This data almost never changes, the greencheck tables are relatively 'narrow', and these checks make up more than 90% of the size of the database.

This is an ideal candidate for exporting as compressed parquet files that we can analyse with something like duckdb.

As a bonus, once the data is safely backed up, we can remove these checks from the main database, reducing the size of the full backups.

**Comment by roald-teunissen** [comment]
Another alternative we can look at is [NoSql.](https://www.ibm.com/cloud/blog/sql-vs-nosql)
Why?
Because:
- Non-relational
- Document based
- Unstructured
- Column oriented
- Very fast because it doesn't ensure ACID but uses the CAP theorem
- "While SQL is valued for ensuring data validity, NoSQL is good when it’s more important that the availability of big data is fast. "

Since we have one table without any required relations to other tables, we can make use of this fact by transforming it into a NoSql database. Since SQL is row oriented, NoSQL is column oriented just like DuckDB is, we can dramatically speed up the querying process. While SQL ensures the ACID principle, NoSQL focusses on the CAP theorem.

In addition to the database infrastructure we choose, we can also use tools like Elasticseach to easily let people search our NoSQL database.

**Comment by mrchrisadams** [comment]
Closing this as we've now managed this migration, and have parquet files generated daily.
