### ISSUE TITLE
[BUG] Error in IP-to-CO2 World data

### ISSUE THREAD

**Issue by fershad** [thegreenwebfoundation/admin-portal#325]
**Describe the bug**
When running an IP address through the IP-to-CO2 Intensity API, the data returned for World (unknown IP) appears to have an incorrect value for `generation_from_fossil`. Or, it is inconsistently formatted compared to country-level data.

Here is what is returned for World

```json
{
            "country_name": "World",
            "country_code_iso_2": "xx",
            "country_code_iso_3": "xxx",
            "carbon_intensity_type": "avg",
            "carbon_intensity": 442.23,
            "generation_from_fossil": 0.62,
            "year": 2021,
            "checked_ip": "104.16.125.175"
        }
```

The returned value of ` "generation_from_fossil": 0.62,` looks strange here. Comparing it to what is returned for a value check of an IP in an actual country ...

``` json
{
            "country_name": "Egypt",
            "country_code_iso_2": "EG",
            "country_code_iso_3": "EGY",
            "carbon_intensity_type": "avg",
            "carbon_intensity": 466.006,
            "generation_from_fossil": 88.87,
            "year": 2021,
            "checked_ip": "163.121.141.38"
        }
```
It seems as though the figure for World should be `62.xx` rather than `0.62`

**To Reproduce**
1. Open a browser
2. Enter `https://api.thegreenwebfoundation.org/api/v3/ip-to-co2intensity/104.16.125.175` into the address bar
3. Observe the result

**Expected behavior**
I expect the number to be between 1 and 100.

**Comment by fershad** [comment]
Can't someone edit the labels - this is pretty low severity.

**Comment by mrchrisadams** [comment]
Ah, good point. I'm not sure why that is (maybe the importer or API I wrote did something weird with World figures?), but the numbers from Ember show the correct formatting. 

See row 4 below in this query on underlying Ember dataset:

https://ember-data-api-scg3n.ondigitalocean.app/ember?sql=select+rowid%2C+country_or_region%2C+country_code%2C+year%2C+variable%2C+generation_twh%2C+capacity_gw%2C+share_of_generation_pct%2C+emissions_mtco2%2C+continent%2C+ember_region%2C+eu_flag%2C+g20_flag%2C+g7_flag%2C+oecd_flag%2C+world_demand_rank%2C+region_demand_rank%2C+oecd_demand_rank%2C+eu_demand_rank%2C+global_fuel_rank%2C+latest_year%2C+coal_deadline%2C+clean_deadline+from+generation_yearly+%0D%0A%0D%0Awhere+variable+%3D+%27Fossil%27+and+year+%3D+%272020%27%0D%0Aorder+by+country_or_region+desc%0D%0Alimit+20

From memory, I think the API might serve a fallback figure when we can't find  info. that might be the source of the 0.62 thing over 61.52 which you might expect.

**Comment by mrchrisadams** [comment]
Ah, good catch @fershad 

Here's the offending code - our fallback expresses 62% as 0.62, with the assumption that every figure is converted from `0.xx` to `xx%` in the responses.

https://github.com/thegreenwebfoundation/admin-portal/blob/582b66ec8132d9d8b84214722a67c1224100883d/apps/greencheck/models/checks.py#L610-L625

GLOBAL_AVG_FOSSIL_SHARE is a constant based on this query.

https://ember-data-api-scg3n.ondigitalocean.app/ember/generation_yearly?_sort=rowid&_facet=year&_facet=variable&country_or_region__exact=World&variable__exact=Fossil&year__exact=2021

The fix turns out to be pretty simple - we change 0.62 to 61.56, as the linked query above suggests

https://github.com/thegreenwebfoundation/admin-portal/blob/582b66ec8132d9d8b84214722a67c1224100883d/apps/greencheck/models/checks.py#L25

If you make that fix, you get bragging rights for having commits in almost all the main greenweb codebases, and this repo is set up to work with gitpod too :D

**Comment by fershad** [comment]
Don't permission to assign things in this repo, but I've raised #326 to fix this.
